In [1]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

iris = load_iris()
X = iris.data

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

print("Original Shape:", X.shape)
print("Reduced Shape:", X_pca.shape)

print("\nTransformed Data:")
print(X_pca[:5])

print("\nVariance Explained:")
print(pca.explained_variance_ratio_)

Original Shape: (150, 4)
Reduced Shape: (150, 2)

Transformed Data:
[[-2.26470281  0.4800266 ]
 [-2.08096115 -0.67413356]
 [-2.36422905 -0.34190802]
 [-2.29938422 -0.59739451]
 [-2.38984217  0.64683538]]

Variance Explained:
[0.72962445 0.22850762]


In [2]:
import numpy as np

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, S, VT = np.linalg.svd(A)

print("Original Matrix:")
print(A)

print("\nU Matrix:")
print(U)

print("\nSingular Values:")
print(S)

print("\nV Transpose:")
print(VT)

Original Matrix:
[[1 2]
 [3 4]
 [5 6]]

U Matrix:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Singular Values:
[9.52551809 0.51430058]

V Transpose:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [3]:
import numpy as np

A = np.array([[1,2],
              [3,4],
              [5,6]])

U, S, VT = np.linalg.svd(A)

Sigma = np.zeros((3,2))
Sigma[:2, :2] = np.diag(S)

A_reconstructed = U @ Sigma @ VT

print(A_reconstructed)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
