In [1]:

import numpy as np

print("Creating a NumPy Array")
x = np.array([1, 2, 3, 4, 5])

print("Array x:")
print(x)

print("\nData Type of x:")
print(type(x))

print("\nShape of x:")
print(x.shape)

print("\nArray using arange():")
arr1 = np.arange(1, 10, 5)
print(arr1)

print("\nArray using linspace():")
arr2 = np.linspace(1, 10, 5)
print(arr2)


print("\nCreating another array:")
x = np.array([1, 2, 3, 4, 5, 6])
print(x)


Creating a NumPy Array
Array x:
[1 2 3 4 5]

Data Type of x:
<class 'numpy.ndarray'>

Shape of x:
(5,)

Array using arange():
[1 6]

Array using linspace():
[ 1.    3.25  5.5   7.75 10.  ]

Creating another array:
[1 2 3 4 5 6]


In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6])
print("1. Reshape (2 x 3):")
print(x.reshape(2, 3))

print("\n2. Size:")
print(x.size)


print("\n3. Shape:")
print(x.shape)

print("\n4. Data Type:")
print(x.dtype)

print("\n5. Item Size:")
print(x.itemsize)

print("\n6. Zeros Array:")
print(np.zeros((4, 5)))

print("\n7. Ones Array:")
print(np.ones((4, 5)))

print("\n8. Random Array:")
a = np.random.random((4, 5))
print(a)

print("\n9. Random Integers:")
x = np.random.randint(0, 10, 5)
print(x)

print("\n10. Shuffled Array:")
np.random.shuffle(x)
print(x)


print("\n11. Random Choice from Array a:")
print(np.random.choice(a.flatten()))


1. Reshape (2 x 3):
[[1 2 3]
 [4 5 6]]

2. Size:
6

3. Shape:
(6,)

4. Data Type:
int32

5. Item Size:
4

6. Zeros Array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

7. Ones Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

8. Random Array:
[[0.56918951 0.33027758 0.63955552 0.63368388 0.81924401]
 [0.04627602 0.55546462 0.89500267 0.07855536 0.95869035]
 [0.28107158 0.5918137  0.06242775 0.47775915 0.86126283]
 [0.11096752 0.05809741 0.97895243 0.75492139 0.4612803 ]]

9. Random Integers:
[1 5 4 9 9]

10. Shuffled Array:
[9 1 5 9 4]

11. Random Choice from Array a:
0.05809741435243998


In [3]:
import numpy as np

a = np.arange(15)

print("Original Array:")
print(a)

print("\nSlicing a[3:9:2]:")
print(a[3:9:2])

print("\nSlicing a[3:]:")
print(a[3:])

print("\nSlicing a[3:8]:")
print(a[3:8])

x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([5, 6, 7, 8, 9, 10])

print("\nArray x:")
print(x)

print("\nArray y:")
print(y)

print("\nAddition:")
print(x + y)

print("\nSubtraction:")
print(x - y)

print("\nMultiplication:")
print(x * y)

print("\nDivision:")
print(x / y)

print("\nMean:", np.mean(x))
print("Median:", np.median(x))
print("Maximum:", np.max(x))
print("Minimum:", np.min(x))
print("Sum:", x.sum())

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Slicing a[3:9:2]:
[3 5 7]

Slicing a[3:]:
[ 3  4  5  6  7  8  9 10 11 12 13 14]

Slicing a[3:8]:
[3 4 5 6 7]

Array x:
[1 2 3 4 5 6]

Array y:
[ 5  6  7  8  9 10]

Addition:
[ 6  8 10 12 14 16]

Subtraction:
[-4 -4 -4 -4 -4 -4]

Multiplication:
[ 5 12 21 32 45 60]

Division:
[0.2        0.33333333 0.42857143 0.5        0.55555556 0.6       ]

Mean: 3.5
Median: 3.5
Maximum: 6
Minimum: 1
Sum: 21


In [4]:
import numpy as np
x = np.array([[1, 2, 3],
              [2, 2, 2]])

print("2D Array:")
print(x)


print("\nRow-wise Sum:")
print(x.sum(axis=1))


print("\nColumn-wise Sum:")
print(x.sum(axis=0))

a = np.array([4, 5, 6])
b = np.array([10, 10, 10])

print("\nVector Multiplication:")
print(a * b)

m1 = np.array([[2, 3],
               [6, 7]])

m2 = np.array([[5, 6],
               [8, 7]])

print("\nMatrix Addition:")
print(np.add(m1, m2))


2D Array:
[[1 2 3]
 [2 2 2]]

Row-wise Sum:
[6 6]

Column-wise Sum:
[3 4 5]

Vector Multiplication:
[40 50 60]

Matrix Addition:
[[ 7  9]
 [14 14]]


In [5]:
# PROGRAM: Ravel and Matrix Operations

import numpy as np

a = np.arange(15).reshape(3,5)

print("Original Matrix:")
print(a)

print("\nFlattened Array:")
print(a.ravel())

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print("\nAddition:")
print(np.add(x,y))


print("\nSubtraction:")
print(np.subtract(x,y))

print("\nMultiplication:")
print(np.matmul(x,y))


print("\nDivision:")
print(np.divide(x,y))

print("\nDeterminant of x:")
print(np.linalg.det(x))

Original Matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Flattened Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[19 22]
 [43 50]]

Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Determinant of x:
-2.0000000000000004
