In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression

X = np.array([[1],
              [2],
              [3],
              [4],
              [5],
              [6],
              [7],
              [8]])

y = np.array([0, 0, 0, 0, 1, 1, 1, 1])
model = LogisticRegression()
model.fit(X, y)
hours = np.array([[7]])
prediction = model.predict(hours)
probability = model.predict_proba(hours)

print("Prediction:", prediction[0])
print("Probability:", probability[0])

#L1 Regularization
import numpy as np
from sklearn.linear_model import LogisticRegression
X = np.array([
    [1, 10],
    [2, 20],
    [3, 30],
    [4, 40],
    [5, 50],
    [6, 60],
    [7, 70],
    [8, 80],
    [9, 90],
    [10, 100]
])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])
model = LogisticRegression(
    penalty='l1',
    solver='liblinear',
    C=1
)
model.fit(X, y)
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)
new_student = np.array([[7, 70]])
prediction = model.predict(new_student)
probability = model.predict_proba(new_student)
print("Prediction:", prediction)
print("Probability:", probability)

Prediction: 1
Probability: [0.05095624 0.94904376]
Coefficients: [[0.         0.04600282]]
Intercept: [-1.36105047]
Prediction: [1]
Probability: [[0.1348025 0.8651975]]


In [3]:
#L2 Regularization
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error
X = np.array([
    [1200, 2, 1, 10, 8],
    [1500, 3, 2, 5, 6],
    [1800, 3, 2, 8, 5],
    [2200, 4, 3, 4, 4],
    [2500, 4, 3, 3, 3],
    [2800, 5, 4, 2, 2],
    [3200, 5, 4, 1, 2],
    [3500, 6, 5, 1, 1],
    [4000, 6, 5, 0, 1],
    [4500, 7, 6, 0, 1],
    [1300, 2, 1, 12, 9],
    [1600, 3, 2, 7, 7],
    [2000, 3, 2, 6, 5],
    [2300, 4, 3, 5, 4],
    [2700, 4, 3, 4, 3],
    [3000, 5, 4, 3, 2],
    [3400, 5, 4, 2, 2],
    [3800, 6, 5, 1, 1],
    [4200, 6, 5, 1, 1],
    [4800, 7, 6, 0, 1]
])
y = np.array([
    45, 60, 72, 90, 105,
    125, 145, 165, 190, 215,
    48, 64, 78, 94, 112,
    135, 155, 180, 200, 230
])
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
model = Ridge(alpha=10)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Coefficients:")
print(model.coef_)

print("\nIntercept:")
print(model.intercept_)
print("\nActual values:")
print(y_test)

print("\nPredicted values:")
print(y_pred)

mse = mean_squared_error(y_test, y_pred)

mae = mean_absolute_error(y_test, y_pred)

print("\nMean Squared Error:", mse)
print("Mean Absolute Error:", mae)

Coefficients:
[13.84265573 11.12211412 11.12211412 -6.07084055 -6.19322373]

Intercept:
130.5

Actual values:
[ 45 180 135  60]

Predicted values:
[ 42.25126959 173.77860562 141.36985938  76.18172909]

Mean Squared Error: 87.17118290508742
Mean Absolute Error: 7.880428314050427


In [4]:
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

X = np.array([
    [1200, 2, 1, 10, 8, 1, 1, 2],
    [1500, 3, 2, 7, 6, 1, 2, 3],
    [1800, 3, 2, 8, 5, 1, 2, 4],
    [2000, 3, 2, 6, 5, 2, 2, 5],
    [2200, 4, 3, 5, 4, 2, 2, 6],
    [2500, 4, 3, 4, 3, 2, 3, 7],
    [2800, 5, 4, 3, 2, 2, 3, 8],
    [3000, 5, 4, 2, 2, 2, 3, 9],
    [3300, 5, 4, 2, 2, 3, 3, 10],
    [3500, 6, 5, 1, 1, 3, 4, 10],
    [3800, 6, 5, 1, 1, 3, 4, 11],
    [4000, 6, 5, 0, 1, 3, 4, 12],
    [1400, 2, 1, 12, 9, 1, 1, 2],
    [1700, 3, 2, 9, 7, 1, 2, 3],
    [2100, 4, 3, 7, 5, 2, 2, 5],
    [2400, 4, 3, 5, 4, 2, 3, 6],
    [2700, 5, 4, 4, 3, 2, 3, 7],
    [3100, 5, 4, 3, 2, 3, 3, 9],
    [3600, 6, 5, 2, 1, 3, 4, 10],
    [4200, 7, 6, 1, 1, 3, 4, 12]
])

y = np.array([
    45, 58, 70, 80, 95,
    110, 128, 140, 155, 170,
    185, 200, 52, 65, 90,
    108, 125, 145, 175, 220
])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
model = ElasticNet(
    alpha=0.1,
    l1_ratio=0.5,
    max_iter=10000
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
features = [
    "Area",
    "Bedrooms",
    "Bathrooms",
    "Age",
    "Distance",
    "Parking",
    "Balcony",
    "Floor"
]

print("Feature Coefficients:")

for feature, coefficient in zip(features, model.coef_):
    print(feature, ":", round(coefficient, 4))

print("\nIntercept:", round(model.intercept_, 4))
print("\nActual values:")
print(y_test)
print("\nPredicted values:")
print(np.round(y_pred, 2))

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nMSE:", round(mse, 4))
print("MAE:", round(mae, 4))
print("R2 Score:", round(r2, 4))

Feature Coefficients:
Area : 18.7592
Bedrooms : 7.7445
Bathrooms : 7.7548
Age : 1.2834
Distance : 5.2055
Parking : 3.1173
Balcony : 4.8366
Floor : 13.7486

Intercept: 128.75

Actual values:
[ 45 145 108  58]

Predicted values:
[ 37.07 147.21 107.97  59.1 ]

MSE: 17.2426
MAE: 2.8173
R2 Score: 0.9892


In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
X = np.array([
    [2, 60, 55, 50, 52],
    [3, 65, 60, 55, 56],
    [4, 70, 65, 60, 61],
    [5, 75, 70, 65, 66],
    [6, 80, 75, 70, 72],
    [7, 85, 80, 75, 77],
    [8, 90, 85, 80, 83],
    [9, 92, 90, 85, 88],
    [10, 95, 95, 90, 93],
    [1, 55, 50, 45, 48],
    [3, 68, 62, 58, 59],
    [4, 72, 68, 63, 64],
    [5, 78, 73, 68, 69],
    [6, 82, 78, 72, 74],
    [7, 86, 83, 77, 79],
    [8, 89, 87, 82, 84],
    [9, 94, 92, 87, 90],
    [2, 63, 58, 52, 55],
    [4, 74, 70, 64, 67],
    [6, 81, 77, 71, 73]
])
y = np.array([
    55, 60, 65, 70, 76,
    81, 86, 91, 96, 50,

    63, 68, 72, 77, 82,
    87, 92, 58, 71, 76
])
features = [
    "Study Hours",
    "Attendance",
    "Assignment Score",
    "Internal Mark",
    "Previous Semester Mark"
]
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("MODEL COEFFICIENTS")
for feature, coefficient in zip(features, model.coef_):
    print(
        feature,
        ":",
        round(coefficient, 3)
    )
print("\nIntercept:")
print(round(model.intercept_, 3))
print("\nACTUAL VS PREDICTED")
for actual, predicted in zip(y_test, y_pred):

    print(
        "Actual:",
        actual,
        " Predicted:",
        round(predicted, 2)
    )

mse = mean_squared_error(
    y_test,
    y_pred
)
mae = mean_absolute_error(
    y_test,
    y_pred
)
r2 = r2_score(
    y_test,
    y_pred
)
print("\nMODEL EVALUATION")
print(
    "Mean Squared Error:",
    round(mse, 3)
)
print(
    "Mean Absolute Error:",
    round(mae, 3)
)
print(
    "R2 Score:",
    round(r2, 3)
)

MODEL COEFFICIENTS
Study Hours : -0.025
Attendance : 1.375
Assignment Score : -1.365
Internal Mark : 4.866
Previous Semester Mark : 6.741

Intercept:
76.0

ACTUAL VS PREDICTED
Actual: 55  Predicted: 55.22
Actual: 58  Predicted: 57.83
Actual: 87  Predicted: 87.21
Actual: 60  Predicted: 59.71

MODEL EVALUATION
Mean Squared Error: 0.052
Mean Absolute Error: 0.223
R2 Score: 1.0
